### PR TITLE
Several changes

### PR DESCRIPTION
**Pull request by editicalu**
Made several changes to make sure that this project stays usable for the coming years.

- Use CMake instead of QMake as it is phased out.
- Update to Qt6, removing deprecated code.
- Use newer SVG images from the KDE project

### CODE REVIEW

**Comment by synio-wesley** [comment]
Thanks @editicalu 

Good to hear that QPasm is still being used. I created this back in 2009 in the year I started as a student at Hasselt University. It was meant to be a replacement for SCASM which was being used back then. In the meantime QPasm is also 12 years old already. Time flies.. I wasn't aware that it's still being used, so I am glad that you are doing a bit of work to keep it usable.

Honestly, I'm focused mainly on web development nowadays, and I don't have Qt installed on my current machine. I looked through the PR changes and I didn't notice anything weird. So I will simply merge the PR.

Thanks for your help!

_PS: Would you be willing to create/release new executables for Windows? (If possible, also Linux and Mac OS X?)_

**Comment by editicalu** [comment]
I will try to make the binaries!

**Comment by editicalu** [comment]
@synio-wesley here are the binaries. You can now make a release. :)
[qpasm_linux.zip](https://github.com/synio-wesley/qpasm/files/7437385/qpasm_linux.zip)
[qpasm_windows.zip](https://github.com/synio-wesley/qpasm/files/7437386/qpasm_windows.zip)
[qpasm_mac.zip](https://github.com/synio-wesley/qpasm/files/7437387/qpasm_mac.zip)

**Comment by editicalu** [comment]
@synio-wesley could you include these in a release? I could then update the AUR package. :)

**Comment by synio-wesley** [comment]
> @synio-wesley could you include these in a release? I could then update the AUR package. :)

I haven't done this yet because the Linux binary needs to be dynamically linked to the needed Qt libraries, but for widest support it should include those dynamically linked libraries (shared object files) and probably also a script to make sure that they will be used. At least this is how I used to do it a long time ago. (Maybe the Linux landscape has changed and this is not necessary anymore?) I think the same issue might be there with the Mac package too, although I would have to test that out.

I don't really have the time to look into it to be honest. But AUR are source built packages, right? So I guess you can simply use the code on Git? Or do you want me to simply tag the current source version without creating/uploading packages? That way you can use the tagged release in AUR probably? I will do that now.

(We could add the Windows package you created to that release as well... that one is working OK and includes the necessary libraries... and I'm guessing most users of this software are running Windows... the ones that aren't are probably smart enough to compile from source anyway..)

**Comment by synio-wesley** [comment]
@editicalu I released a new version, and I also added the binaries. I put a note there regarding the Linux/Mac packages, so users can decide for themselves to use them or not.

**Comment by editicalu** [comment]
Yes. The AUR compiles from source, but it is a lot cleaner to download a git tag.

I didn't think of the dynamic linking issue. But if the users can't figure it out, it is always possible to use the 1.3 release without those problems.

**Pull request merged**
